version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  inventory-api:
    build: ./inventory-api
    ports:
      - "3001:3001"

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
