name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # change if your default branch is different

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Test inventory-api
        working-directory: ./RetailOps/inventory-api
        run: |
          npm install
          echo "No tests yet..." && exit 0

      - name: Test product-service
        working-directory: ./RetailOps/product-service
        run: |
          npm install
          echo "No tests yet..." && exit 0

      - name: Test frontend
        working-directory: ./RetailOps/frontend
        run: |
          npm install
          echo "No tests yet..." && exit 0

  build-and-push:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push inventory-api image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/inventory-api:latest ./RetailOps/inventory-api
          docker push ${{ secrets.DOCKER_USERNAME }}/inventory-api:latest

      - name: Build and push product-service image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/product-service:latest ./RetailOps/product-service
          docker push ${{ secrets.DOCKER_USERNAME }}/product-service:latest

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./RetailOps/frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy reminder
        run: |
          echo "Automatic deployment to Azure not configured."
          echo "Please deploy manually using Azure CLI as documented."
